### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by fanzhitaophd** [abhi1kumar/LUVLi#1]
Hi, will you share your inference code and trained weights file? I'd like to try on some my own images. Thanks!

**Comment by abhi1kumar** [comment]
The links to the trained models for all the splits have now been added to README file. 

The inference code for different datasets is already there. Please see `scripts_evaluation.sh` The inference on your own images requires cropping the images first, converting them to json and then doing a forward pass using a model and the json

**Comment by waleedrazakhan92** [comment]
> Hi, will you share your inference code and trained weights file? I'd like to try on some my own images. Thanks!

@fanzhitaophd did you manage to run the inference?
